version: "3"
services:
  webpdl2ork:
    image: ghcr.io/pd-l2ork/pd-l2ork # Pre-built GitHub image
    # build: # Local Image
    #   context: .
    #   dockerfile: webpdl2ork.Dockerfile
    #ports:
    #  - "3000:80" # Serve without proxy
    environment:
      - PORT=80
      - PATCH_PATH=public/patches
      - VIRTUAL_HOST=l2ork.music.vt.edu # Sets the domain name being used for pd-l2ork
    volumes:
      - ./emscripten/projects/WebPdL2Ork/public:/WebPdL2Ork/public/patches:ro # The first path sets the folder where patches will be loaded from
    restart: unless-stopped
    container_name: webpdl2ork
  nginx:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "3000:443" # Serve using https (requires certificates)
      # - "3000:80" # Serve using http
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
    restart: unless-stopped
    container_name: nginx-proxy
    environment:
      - LOG_FORMAT=$$remote_addr - $$remote_user [$$time_local] "$$request" $$status $$body_bytes_sent "$$http_referer" "$$http_user_agent" $$host $$request_time $$upstream_cache_status
