version: '3'
services:
  webpdl2ork:
    build: 
      context: .
      dockerfile: webpdl2ork.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./emscripten/projects/WebPdL2Ork/public:/WebPdL2Ork/public/patches:ro
    restart: unless-stopped
    container_name: webpdl2ork