name: Testing build pipelines

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: deb
        path: Pd-L2Ork-*.deb
        if-no-files-found: error

  # build-macos:
  #   runs-on: macos-13
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: make
  #     run: make
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: deb
  #       path: Pd-L2Ork-*.dmg
  #       if-no-files-found: error

